ns1-terraform/terraform-provider-ns1

vendor/gopkg.in/ns1/ns1-go.v2/LICENSE.txt, vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data/meta.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data/string.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/zone.go, vendor/vendor.json
```
govendor fetch gopkg.in/ns1/ns1-go.v2/...@a602ff24bf5ec60e02462e503f02ddba81b68615
make test
```
=> vendor: gopkg.in/ns1/ns1-go.v2/...@a602ff24bf5ec60e02462e503f02ddba81b68615

ns1/examples/record.tf
* Correcting syntax error (CNAME record type w/ IP4 answer)
* Adding examples for regions, country, state, and province codes.
=> Adding some examples to the docs

ns1/resource_zone.go
=> Allowing zone networks to be specified

Gopkg.lock, Gopkg.toml, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data/meta.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/record.go
pulling in the latest from the ns1-go project after this PR got merged: https://github.com/ns1/ns1-go/pull/50
=> pulled in latest from ns1-go

ns1/data_source_zone.go, ns1/data_source_zone_test.go, ns1/provider.go, ns1/resource_zone.go, website/docs/d/zone.html.markdown, website/ns1.erb
This adds a first data source for the DNS zone.
I did some function renaming in the equivalent resource file to avoid namespace issues and to follow practices in other TF modules.
=> Add NS1 Zone Data Source

go.mod, go.sum, ns1/data_source_zone.go, ns1/data_source_zone_test.go, ns1/resource_zone.go, ns1/resource_zone_test.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/zone.go, vendor/modules.txt, website/docs/d/zone.html.markdown, website/docs/r/zone.html.markdown
* Updates ns1-go dependency to latest version
* Adds support to resource/ns1_zone for specifying additional primary
IPs
* Adds support to datasource/ns1_zone for additional primary IPs
* Adds documentation to resource/ns1_zone for missing and new attributes, fixes #41 
* Adds documentation to datasource/ns1_zone for missing and new attributes
=> Adds support for additional primary IPs

README.md, website/docs/d/zone.html.markdown, website/docs/index.html.markdown, website/docs/r/apikey.html.markdown, website/docs/r/datafeed.html.markdown, website/docs/r/datasource.html.markdown, website/docs/r/monitoringjob.html.markdown, website/docs/r/notifylist.html.markdown, website/docs/r/record.html.markdown, website/docs/r/team.html.markdown, website/docs/r/user.html.markdown, website/docs/r/zone.html.markdown
* Add a Known Issues/Roadmap section to the top-level README
* Document meta fields for ns1_record, and import
* Ensure attributes section is present for each resource
* misc minor improvements throughout
=> flesh out documentation a bit

ns1/resource_zone_test.go
snakes to camels, and spruce up some error messages a bit
=> minor refactor of testAccCheckNSRecord

go.mod, ns1/resource_apikey.go, ns1/resource_apikey_test.go, ns1/resource_datafeed.go, ns1/resource_datafeed_test.go, ns1/resource_datasource.go, ns1/resource_datasource_test.go, ns1/resource_monitoringjob.go, ns1/resource_monitoringjob_test.go, ns1/resource_notifylist.go, ns1/resource_notifylist_test.go, ns1/resource_record.go, ns1/resource_record_test.go, ns1/resource_team.go, ns1/resource_team_test.go, ns1/resource_user.go, ns1/resource_user_test.go, ns1/resource_zone.go, ns1/resource_zone_test.go
=> Update resource state management to properly handle disappearing resources

ns1/resource_record.go, ns1/resource_record_test.go
also resolves this for other []string fields. Closes #111
=> Fix for IP Prefix ordering

ns1/resource_user.go, ns1/resource_user_test.go
Add ValidationFunc for username so we can catch issues in the "plan"
stage.
Also replace some tab literals where they were mixed in with spaces
in format strings.
=> INT-218: validate username field

README.md
Updates README to reflect new location of provider and special considerations required as a result of repo location move
=> Update README for 0.13 release

ns1/data_source_record_test.go
Fixes failing record data source test.
=> Create zone fixture for test

.gitignore
Add the built binary to .gitignore file, so we don't accidentally commit this.
=> Add the built binary to .gitignore file

go.mod, go.sum, ns1/resource_record.go, ns1/resource_record_test.go
I have added the code changes to add support for DNS record with DNSSEC (DS) type
=> Adding support for DNS record with DNSSEC (DS) type

ns1/resource_datafeed.go, ns1/resource_datafeed_test.go
Add a layer to convert the test_id as an int
=> INBOX-1140

website/docs/r/monitoringjob.html.markdown, website/docs/r/team.html.markdown
add documentation for: 
DAITDS-103
MON-130
=> Chore/documentation DAITDS-103 MON-130

ns1/resource_monitoringjob.go, ns1/resource_monitoringjob_test.go
hot fix added tls_add_verify to be converted as boolean, also added testacc for this case
=> DAITDS-193 added tls_add_verify to be converted as boolean

ns1/resource_apikey.go, ns1/resource_apikey_test.go, ns1/resource_team.go, ns1/resource_team_test.go, ns1/resource_user.go, ns1/resource_user_test.go
Ticket link: [DAITDS-194](https://ns1inc.atlassian.net/browse/DAITDS-194)
Changed the ip_whitelist type from TypeList to TypeSet, so the order isn't relevant.
=> DAITDS-194

ns1/examples/datafeed.tf, ns1/examples/record.tf, ns1/examples/user.tf, website/docs/index.html.markdown, website/docs/r/apikey.html.markdown, website/docs/r/datafeed.html.markdown, website/docs/r/pulsar_job.html.markdown, website/docs/r/record.html.markdown, website/docs/r/user.html.markdown
Update documentation and examples removing deprecated interpolation specified in the Jira Ticket [DAITDS-129](https://ns1inc.atlassian.net/browse/DAITDS-129).
=> DAITDS-129

ns1/resource_record.go, ns1/resource_record_test.go, website/docs/r/record.html.markdown
@Zach-Johnson There was no more changes, it's just a test to try to link this PR with the Jira ticket
=> INBOX-1443 -  Terraform provider api subdivision formatting inconsistency

ns1/resource_record.go, ns1/resource_record_test.go
Written acceptance tests and supressed difference between zone and domain of terraform state and Terraform file.
This PR works together with PR#157 in ns1-go client repository to complete TEG-226 ticket
@Zach-Johnson please review
=> TEG-226 / Terraform capitalization

CHANGELOG.md
New release to include https://github.com/ns1-terraform/terraform-provider-ns1/pull/213
=> INBOX-1736/Bump to 1.12.7

CHANGELOG.md
=> version 1.12.8 CHANGELOG

go.mod, go.sum, ns1/provider.go, ns1/resource_dns_view.go, ns1/resource_dns_view_test.go, website/docs/r/dns_view.html.markdown
=> Add support for DNS views. Requires updated `ns1-go` version

CHANGELOG.md, ns1/config.go
BUG FIXES
* Update instead of delete/recreate when changing link attribute of DNS record
* Fix documentation typo
=> INBOX-2220/Release 1.13.1-pre1

ns1/permissions.go, ns1/resource_apikey_test.go, ns1/resource_user_test.go
* permissions schema  fixes
* test fixes - properly match error responses
=> INBOX-2213/fix perm schema, fix tests

ns1/config.go, ns1/permissions.go, ns1/resource_apikey_test.go, ns1/resource_team.go, ns1/resource_user_test.go
* user security flags actually default to True in the API
* fix corner cases where DHCP and IPAM flags weren't being set
* add debugging for HTTP responses
* refresh team object after creation to work around incomplete initial response
=> match permissions defaults with API defaults

ns1/config.go, ns1/resource_record.go, ns1/resource_record_test.go, ns1/resource_team_test.go, ns1/resource_user.go
* HTTP logging - include request/response time with milliseconds so we can see where API calls overlapped
* DNS record metadata - regions now sorted alphabetically to prevent false differences
* more acceptance test fixes
=> Misc fixes - tests, metadata region sort, logging

ns1/examples/permissions.tf, website/docs/r/apikey.html.markdown, website/docs/r/team.html.markdown, website/docs/r/user.html.markdown
Corrects documentation issue described in #228.
=> Daitds-406/doc

website/docs/index.html.markdown
=> INFO-505/docs

ns1/resource_apikey.go, ns1/resource_apikey_test.go, ns1/resource_application_test.go, ns1/resource_datasource_test.go, ns1/resource_dns_view_test.go, ns1/resource_monitoringjob_test.go, ns1/resource_notifylist_test.go, ns1/resource_tsig_key_test.go, website/docs/r/apikey.html.markdown
* add APIKey import support
* additional import testing
=> PERSONA-260/imports-and-import-testing

ns1/permissions.go
Fix for issue #196
Fix for issue #197
=> DAITDS-290/DAITDS-291 permissions fixes

ns1/resource_zone.go, ns1/resource_zone_test.go
* Don't try to delete NS records on linked zones.
=> INBOX-2028/fix autogenerate ns record issue with linked zones

go.mod, go.sum, ns1/resource_apikey.go, ns1/resource_monitoringjob.go, ns1/resource_notifylist.go, ns1/resource_team.go, ns1/resource_user.go
* go back to using the app-specific error codes now that they are fixed in latest ns1-go library
=> Inbox 2228/use error codes again

.gitignore, go.mod, go.sum, ns1/data_source_networks.go, ns1/data_source_networks_test.go, ns1/provider.go, website/docs/d/networks.html.markdown, website/ns1.erb
This PR includes:
- Networks datasource
- Acceptance tests
- Documentation
=> Adding Networks Data source

CHANGELOG.md, go.mod, go.sum, ns1/config.go, ns1/resource_record.go, ns1/resource_record_test.go
- Bump go version to accept empty filter list
- Add test
=> INBOX-2625 - Add test for empty filter list & bump ns1-go version

CHANGELOG.md, go.mod, go.sum, ns1/config.go, ns1/resource_record_test.go
- Adds tests for POST without tags and with
- Bump SDK version
=> release-v2.0.10

.github/workflows/release.yml, CHANGELOG.md
GoReleaser introduced a breaking change in v2
=> Fix goreleaser dependency

CHANGELOG.md, go.mod, go.sum, ns1/config.go, ns1/resource_zone.go, ns1/resource_zone_test.go
New 
Adds support for `notify_only` field in secondary zones config
Adds support for `signed_notifes` field in tsig config
=> PRODUCT-2321/Features

website/docs/r/record.html.markdown
I've been asked if "link" is supposed to be an id, so explaining that it's a domain; but then domain can mean different things so doing it in more words 😃
=> Improve doc on record "link" field

CHANGELOG.md, ns1/config.go, ns1/examples/alert.tf, ns1/resource_alert.go, ns1/resource_alert_test.go, website/docs/r/alert.html.markdown
Adding support for account/usage alerts via a data resource block.
=> Add usage alerts support
