ns1-terraform/terraform-provider-ns1

website/docs/index.html.markdown
The current documentation provides the wrong env variable. It's not NS1_API_KEY, but NS1_APIKEY. Terraform kept asking me for the API despite having set it in my environment:
```
❯ terraform plan
provider.ns1.apikey
The ns1 API key, this is required
Enter a value:
```
After searching through the source code and finding the correct key, it was working.
=> Fix API key environmental variable documentation

CHANGELOG.md, ns1/resource_zone.go
The NS1 API does not require the networks field and provides a sane default. Currently when a user does not specify a value in their config, terraform always shows this as a difference. To fix this undesirable behavior, this patch makes the field computed. This change should be backwards compatible for existing users.
=> Make 'networks' field computed for zone resources

CHANGELOG.md, ns1/resource_record.go
This behavior was preventing customers from being able to specify a boolean value, which is needed for a number of filter configs. This change should be backwards compatible because our API will accept strings of digits wherever an int is called for.
=> Don't try to convert filter config values to ints

ns1/resource_datafeed_test.go, ns1/resource_monitoringjob_test.go, ns1/resource_notifylist_test.go, ns1/resource_record_test.go, ns1/resource_user_test.go
Updates schema of Terraform configs in acceptance tests for compatibility with Terraform v0.12.  Output of `make testacc` with provider compiled against `terraform@v0.12.0-beta1`
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?       github.com/terraform-providers/terraform-provider-ns1   [no test files]
=== RUN   TestAccDataSourceZone_basic
--- PASS: TestAccDataSourceZone_basic (7.12s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccDataFeed_basic
--- PASS: TestAccDataFeed_basic (10.86s)
=== RUN   TestAccDataFeed_updated
--- PASS: TestAccDataFeed_updated (13.66s)
=== RUN   TestAccDataSource_basic
--- PASS: …
```
=> Update acceptance tests for Terraform 0.12 compatability

README.md, ns1/resource_record.go, ns1/resource_record_test.go
To partially address #19, force a deterministic ordering of the regions in a record.  I say partially, because this assumes the regions in the terraform template are already sorted.
=> Sort regions inside Records

ns1/resource_user.go
The current state of the provider is to just attempt to update the username when it is changed. This results in the error, `500 We found a problem processing this request. Please contact support.` To fix this, require a destroy and create for the user if the username is to be updated.
=> Usernames cannot be changed in NS1 so must force new

go.mod, go.sum, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data/meta.go, vendor/modules.txt
Updates ns1-go module to latest version.
This integrates bugfixes to allow for resolution of #53 when assigning the value of a key in a meta block to the raw JSON string of a feed (i.e. `weight = "{\"feed\":\"${ns1_datafeed.foobar.id}\"}"`).
This workaround can also be used to resolve #35 until Terraform 0.12 is released and enhanced support for nested data structures make their way into the SDK, at which point a refactor of our schema will be required.
=> Update ns1-go dependency to latest version

.gitignore, go.mod, go.sum, ns1/resource_record_test.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data/meta.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/stat.go, vendor/modules.txt
* Update ns1-go dependency to fix crash when passing multiple `ip_prefixes` as a comma delimited string
* Add test for attributes in record meta block to verify `ip_prefixes` fix works as intended
=> Fix IP Prefixes validation

CHANGELOG.md, ns1/resource_notifylist.go, ns1/resource_notifylist_test.go
Adds support and tests for all notifier types supported by NS1 SDK.  Returns error on unsupported notifier type.  Resolves #34
=> Extended Notification Support

CHANGELOG.md, ns1/data_source_zone_test.go, ns1/resource_zone.go, ns1/resource_zone_test.go
Help prevent collisions, since zone names need to be unique
Bonus: typo fix
=> randomize zone name in acc tests

ns1/config.go
Add option to enable request body logging via `NS1_DEBUG` env var.  To view logs, Terraform debug logging must be enabled (i.e. via `TF_LOG=DEBUG`)
=> Add Request Logging

ns1/resource_record.go, ns1/resource_record_test.go
The list of locations provided in the meta of the regions block were
depending on a specific order that was difficult to reproduce, leading
to having the terraform provider finding differences where there was
not any.
This fixes it by comparing the contents of the 'georegion', 'country',
'us_state' and 'ca_province' meta by first splitting the values on
commas, and verifying that they both contain the same elements.
=> Record: ignore the order of the locations provided in the regions blocks

ns1/resource_zone.go, ns1/resource_zone_test.go, website/docs/r/zone.html.markdown
Fields `refresh`, `retry`, `expiry`, and `nx_ttl` should not be
settable on secondary zones. API is now enforcing this on create
by discarding any changes from default. It had already been
discarding _updates_ to these fields on an existing secondary zone.
* Fix a broken test that was setting these fields on a secondary.
* Add ConflictsWith to the fields to prevent this, and update docs.
=> BUGFIX: disallow setting SOA fields on secondary zones

README.md, go.mod, go.sum, ns1/data_source_zone.go, ns1/data_source_zone_test.go, ns1/resource_zone.go, ns1/resource_zone_test.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/dnssec.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/dnssec.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/zone.go, vendor/modules.txt, website/docs/d/zone.html.markdown, website/docs/index.html.markdown, website/docs/r/zone.html.markdown
* Ensure that leaving DNSSEC unset, or removing the setting, doesn't change
existing value.
* pre-check for DNSSEC tests tries to create a zone with DNSSEC=true,
if it fails due to account permissions, we skip the test.
=> INT-43 support toggling DNSSEC on zones

ns1/data_source_zone.go, ns1/resource_zone.go
resource_zone:
* `resourceToZoneData` -> `resourceDataToZone`: consistent with
naming in other files
* Remove "resource" prefix from CRUD funcs - these were to
differentiate between similar funcs for the "data_source" version
of zone, but we don't need counterparts for these.
data_source_zone:
* Use the `zoneRead` func from `resource_zone` rather than defining
an (identical) "data_source" version.
=> cleanup: rename/reuse "zone" funcs

go.mod, go.sum, vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/modules.txt
Picks up a divide by zero fix for handling rate limiting, should help
with high cardinality imports and changesets.
=> INT-49: bump version of ns1 SDK

.travis.yml, README.md
1.11 still works but we're movin' on!
=> bump go version for CI and README (1.11+ to 1.12+)

ns1/resource_zone.go
Defaults for these fields from Optional/Default to Optional/Computed,
so we don't send them when unset. This was breaking CIDR ranges for
IP, as the port cannot be explicitly set with them.
=> INT-24: secondaries port and notify defaults

ns1/resource_zone.go, ns1/resource_zone_test.go
This new parameters is only used on creating a zone and allows to
prevent for NS records to be created automatically, which would
prevent users to create those records by themselves. This does it
by actually removing the auto-created NS record when the option
is set to 'false'. By default, the option is set to 'true'. We
also ignore any change to that value after creation, as it will
not imply any change to the deployed resource.
Following the discussion we've had on https://github.com/terraform-providers/terraform-provider-ns1/pull/77
=> ns1_zone: add a new 'autogenerate_ns_record' parameter defaulting to 'true'

ns1/resource_zone.go
When importing a zone, we need to set autogenerate_ns_record or
terraform thinks the resource is dirty. This was also causing acc
test failures.
=> import zone autogenerate_ns_record fix

go.mod, go.sum, ns1/config.go, ns1/provider.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/headers.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/zone.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/modules.txt, website/docs/index.html.markdown
* Adds `rate_limit_parallelism` option. This initiates an alternate
strategy for avoiding 429s from rate limiting in the NS1 API.
* Improve documentation around provider arguments and environment
variables
* Pick up latest SDK, go mod vendor, go mod tidy
=> Add config option to use an alternate rate limit strategy

GNUmakefile, README.md
While working issue #38, I made a couple small fixes to the README.md file and make file.  These seemed like low-hanging fruit while I was working.
(1) There were a couple lines that ran off to the right.  I wrapped them so they were consistent with the rest of the README.md formatting and easier to read when looking at multiple files at the same time.
(2) I added `make clean` as a rule in the make file so we can do things like `make clean build` and know the earlier artifact was removed prior to building a new one.
Happy Hacking!
=> Minor Documentation and Makefile fixes 

ns1/data_source_dnssec_test.go, ns1/resource_datafeed_test.go, ns1/resource_datasource_test.go, ns1/resource_monitoringjob_test.go, ns1/resource_notifylist_test.go, ns1/resource_record_test.go, ns1/resource_user_test.go, ns1/resource_zone_test.go
This pull request addresses [issue #92](https://github.com/terraform-providers/terraform-provider-ns1/issues/92).
Changed capitalization with minimal change, adding context where it helped to also satisfy this standard and make the error message more descriptive.
=> Change Error strings to comply with golang standard.

README.md, ns1/resource_record.go, ns1/resource_record_test.go, website/docs/r/record.html.markdown
Adds validation to the zone and domain fields on a record to more clearly indicate invalid inputs containing leading or trailing dots
=> records: handle zone/domain strings with leading/trailing dots

ns1/permissions.go, ns1/resource_apikey.go, ns1/resource_apikey_test.go, ns1/resource_team.go, ns1/resource_team_test.go, ns1/resource_user.go, ns1/resource_user_test.go, website/docs/r/apikey.html.markdown, website/docs/r/user.html.markdown
I was able to get the diffs to suppress when a user or api key is part of a team. There is some quirkiness when something is removed from teams altogether though, because the user/key inherits the permissions it had previously, so you potentially have to run a second `apply` in order to update the permissions on the user/key to what is set in the config for that user/key. I documented that piece of it. 
This should close #15
=> Clean up permission diffs on users and api keys

website/docs/d/zone.html.markdown, website/docs/r/zone.html.markdown
Documentation update to clarify `primary` and `additional_primaries` fields only support IPv4 addresses.  Closes #106.
=> Update Documentation For IPv4 Only Fields

go.mod, go.sum, ns1/config.go, ns1/permissions.go, ns1/permissions_migrations.go, ns1/provider.go, ns1/resource_apikey.go, ns1/resource_apikey_migrations.go, ns1/resource_apikey_test.go, ns1/resource_team.go, ns1/resource_team_migrations.go, ns1/resource_team_test.go, ns1/resource_user.go, ns1/resource_user_migrations.go, ns1/resource_user_test.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/account_apikey.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/account_team.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/account_user.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/ddi.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/apikey.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/permissions.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/team.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/user.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/answer.go, vendor/modules.txt, website/docs/index.html.markdown, website/docs/r/apikey.html.markdown, website/docs/r/team.html.markdown, website/docs/r/user.html.markdown
Would like to get some thoughts on the state migration. There didn't seem to be a way to add DDI permissions transparently to users of SaaS without a migration, because the DDI permissions still get defaulted to false, so if you were a SaaS user and upgraded TF, you would see a diff on the new permissions being added and set to false (even though they weren't actually propagating to the API). Doesn't seem like a huge deal, but it seemed confusing to me, so I added this migration to properly handle it. Now if a user upgrades to this version, they shouldn't see a diff on their permissions, but it also might be overkill.
=> ddi permission support and ip whitelist support

README.md, website/docs/r/apikey.html.markdown, website/docs/r/datafeed.html.markdown, website/docs/r/datasource.html.markdown, website/docs/r/monitoringjob.html.markdown, website/docs/r/notifylist.html.markdown, website/docs/r/record.html.markdown, website/docs/r/team.html.markdown, website/docs/r/user.html.markdown, website/docs/r/zone.html.markdown
Some of the README examples are out-of-date/wrong. We didn't really
notice because the "real" docs are part of the repo and are published
on release, and we're not usuallty looking at the the README for a
source of truth.
Rather than cleaning up the README examples and having to keep them up
to date with future changes, just replace the examples with links to
the better maintained docs.
=> replace examples in README with links to docs

ns1/resource_record.go, ns1/resource_record_test.go
slightly modified from https://github.com/terraform-providers/terraform-provider-ns1/pull/122
resolves the issue of filter and meta fields not being converted to strings properly and causing issues being stored in TF state
=> Fix meta and filter fields

ns1/resource_record.go, ns1/resource_record_test.go
a record's answer's meta's "up" field can be a feed pointer, recently
added diff suppression always evaluated these as "unchanged"
handle this case, and add a test exercising this kind of record answer
meta up
=> fix meta diff suppress up

website/docs/r/record.html.markdown
The TTL value is represented in seconds and stating that helps avoid confusion amongst consumers of this provider/resource.
=> Update Record page to state TTL value type

ns1/permissions.go
Deprecates attribute for obsolete permission `manage_plan`
=> Deprecate obsolete permission

ns1/resource_record.go
convert float64 values in config maps to string as sometimes NS1 api will return a numeric value as a number and sometimes as a string
fixes #132 
I have validated that when the value arrives as numeric and we push an update that has the value as a string the NS1 api does the correct thing.
=> fix float64/string value conversion issue with config

go.mod, go.sum, vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data/meta.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/zone.go, vendor/modules.txt
Hi,
There is need to upgrade go-ns1 to 2.4.2 in order to support `cost` field inside answers meta
=> upgrade go-ns1 to 2.4.2

ns1/data_source_record.go, ns1/data_source_record_test.go, ns1/provider.go, website/docs/d/record.html.markdown
PR to add an `ns1_record` data source.
Local Testing Output
Terraform
```
data "ns1_zone" "za-test" {
zone = "za.test"
}
data "ns1_record" "abc" {
zone = data.ns1_zone.za-test.zone
domain = "abc.${data.ns1_zone.za-test.zone}"
type = "CNAME"
}
resource "ns1_record" "xyz" {
zone = data.ns1_zone.za-test.zone
domain = "xyz.${data.ns1_zone.za-test.zone}"
type = "CNAME"
answers {
answer = data.ns1_record.abc.domain
meta = {
up = true
}
}
}
```
Plan Output
```
data.ns1_zone.za-test: Refreshing state...
data.ns1_record.abc: Refreshing state...
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "ns1_record" "xyz" {
+ domain            = "xyz.za.test"
+ id …
```
=> Add ns1_record data source

ns1/resource_monitoringjob.go
The API expects this value to be of type boolean, anything else including the string variant "true" is rejected.
```
{
"message": "monitoring job config error: \"true\" invalid for option \"tls_skip_verify\""
}
```
Tested locally
```
resource "ns1_monitoringjob" "test" {
name            = "ZA TEST"
active          = true
frequency = 30
job_type = "http"
regions = ["sin", "sjc", "lga", "ams", "syd"]
config = {
tls_skip_verify = true
authorization   = null
connect_timeout = 5
idle_timeout    = 3
method          = "GET"
url             = "http://localhost"
}
rules {
key        = "status_code"
comparison = "=="
value      = "200"
}
}
```
Plan
```
Terraform will perform the following actions:
+ resource "ns1_monitoringjob" "test" {
+ active        = true
+ config        = {
+ "connect_timeout" …
```
=> Fix bug with `tls_skip_verify` not being type casted correctly

website/docs/r/apikey.html.markdown
Having the key field as "Required" has caused some confusion for customers as it is created by NS1, not by the user.
=> Update apikey documentation

ns1/resource_apikey.go, ns1/resource_apikey_test.go
There a is a bug where the `key` attribute is empty for an `apikey` resource that is a member of a team.
This is due to the fact that permissions are inherited from teams, so an additional GET was required on create to read the inherited permission state.  However, `key` attribute is only sent from API on the initial creation of the apikey, so the results of the 2nd GET do not include them, and the returned resource data does not include `key`
This PR fixes this issue by adding the `key` attribute received in the initial create back to the results of the 2nd GET, before returning the resource data.
=> Fix key missing on apikey when joined to team

go.mod, go.sum, vendor/gopkg.in/ns1/ns1-go.v2/rest/client.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/account/permissions.go, vendor/gopkg.in/ns1/ns1-go.v2/rest/model/dns/answer.go, vendor/modules.txt
The GO SDK was hitting the rate limit when the HTTP request was returning with errors because the rate limit function was being executed after the HTTP error checking
=> PERSONA-180 change ns1 go sdk to a newer version to fix 4XX issues

ns1/data_source_dnssec.go, ns1/error_handler.go, ns1/resource_apikey.go, ns1/resource_datafeed.go, ns1/resource_datasource.go, ns1/resource_monitoringjob.go, ns1/resource_notifylist.go, ns1/resource_record.go, ns1/resource_team.go, ns1/resource_user.go, ns1/resource_zone.go
The go SDK removes some request and response information from the messages. This commit will add some information like URL, method, and message from the request/response
=> PERSONA-179/change terraform output message to add verbose

ns1/permissions.go, ns1/resource_user_test.go
Terraform set default value to false, but in some cases **p.Security** was not initialized, so the struct sent in the request didn't have the p.Security default values, so it was using the API default value, which is true.
Even if setting **security_manage_global_2fa = false**, because GetOk returns false if the value is equal to Zero-value, how Bool zero value is false, it never sets **security_manage_global_2fa = false**.
The change forces the p.Security to be initialized if it wasn't and change the permission to true if the parameter is passed.
=> Creating ns1_user with security_manage_global_2fa true even if set to false

website/docs/r/apikey.html.markdown, website/docs/r/team.html.markdown, website/docs/r/user.html.markdown
PR about [DAITDS-195 - Terraform Docs: ip_whitelist and ip_whitelist_strict are missing](https://ns1inc.atlassian.net/browse/DAITDS-195).
Got the information from [NS1 API Documentation](https://ns1.com/api).
=> DAITDS-195 - Terraform Docs: ip_whitelist and ip_whitelist_strict are missing

ns1/resource_record.go
If used metadata with an empty value in terraform file, instead of removing the previous metadata on NS1, terraform tries to apply the empty field causing an error from API. By forcing all fields to be nil if there is an empty value we can guarantee the correct behavior
=> DAITDS-200

ns1/resource_pulsar_job.go
When reading resource data from the API, I believe the intent is to update the Terraform resource data. It looks like this one line was doing the opposite, causing Terraform to say there are changes to be applied when there are not because Terraform state was not being written. This was also affecting the result of `terraform import`. If you import a Pulsar job and examine the state file, many of its attributes are `null` which should not be.
Terraform state after `import`:
```json
{
"mode": "managed",
"type": "ns1_pulsarjob",
"name": "***",
"provider": "provider[\"registry.terraform.io/ns1-terraform/ns1\"]",
"instances": [
{
"schema_version": 1,
"attributes": {
"active": null,
"app_id": "***",
"blend_metric_weights": null,
"community": null,
"config": null,
"customer": null,
"id": "***", …
```
=> Update job resource data on read

ns1/resource_record.go, ns1/resource_record_test.go
Most subdivision have a format "Country-Subdivision" but there are 2 (Norway NO and Singapore SG) that also contains the Country code in the subdivisions resulting in a double country code "Country-Country-Subdivision". 
The code was splitting the string by dashes which was resulting into 3 substring and it was failing.
I don't know why they have different format but the correct fix would be updating the subdivision to have all in the same format. These would cause more problems and will require some DB migrations
In order to fix it quickly we just need to use the splitN and limit to 2 substrings that this PR is addressing
@Zach-Johnson please review this PR
=> Fix subdivision split by dash

ns1/resource_apikey.go
The goal is to prevent exposing secrets in TF commmand outputs.
Especially important in CD/CI pipelines for example.
=> Make apikey key attribute sensitive

ns1/data_source_zone.go, ns1/resource_zone_test.go
And remove unused function `dataSourceZoneToResourceData`, as this data source uses the function `zoneRead` that lives in the `resource_zone.go` file.
=> Fix some Zone acceptance test assertions

ns1/examples/monitoringjob.tf, ns1/resource_monitoringjob_test.go, website/docs/r/monitoringjob.html.markdown
* Show proper use of send strings in examples - backslashes escapes are required
* Fix monitoring job acceptance tests
```
$ TF_ACC=1 /usr/local/go/bin/go test -v -run TestAccMonitoring* -shuffle on
-test.shuffle 1665615565084214079
=== RUN   TestAccMonitoringJob_basic
--- PASS: TestAccMonitoringJob_basic (2.62s)
=== RUN   TestAccMonitoringJob_ManualDelete
--- PASS: TestAccMonitoringJob_ManualDelete (2.95s)
=== RUN   TestAccMonitoringJob_updated
--- PASS: TestAccMonitoringJob_updated (0.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ns1/ns1	6.351s
```
=> Monitoring tests fixed

website/docs/r/pulsar_job.html.markdown
This change addresses an inconsistency in the docs. The correct name seems to be `ns1_pulsarjob`
=> docs: rename ns1_pulsar_job -> ns1_pulsarjob

ns1/resource_zone_test.go, ns1/test_funcs.go
zone acceptance tests now pass except for known issue deleting zones with TSIG:
```
--- PASS: TestAccZone_basic (3.44s)
=== RUN   TestAccZone_updated
--- PASS: TestAccZone_updated (3.13s)
=== RUN   TestAccZone_primary_to_secondary_to_normal
--- PASS: TestAccZone_primary_to_secondary_to_normal (6.78s)
=== RUN   TestAccZone_secondary_to_primary_to_normal
--- PASS: TestAccZone_secondary_to_primary_to_normal (3.07s)
=== RUN   TestAccZone_dnssec
--- PASS: TestAccZone_dnssec (6.49s)
=== RUN   TestAccZone_hostmaster
--- PASS: TestAccZone_hostmaster (2.85s)
=== RUN   TestAccZone_TSIG
testing.go:701: Error destroying resource! WARNING: Dangling resources
may exist. The full state and error is shown below.
Error: errors during apply: DELETE …
```
=> zone acceptance tests tweak

CHANGELOG.md, go.mod, go.sum, ns1/config.go
Upgrade to ns1-go v2.7.1 to get fix for rate-limit divide-by-zero error.
=> release 1.13.2-pre1 (prerelease)

CHANGELOG.md, go.mod, go.sum, ns1/config.go, ns1/provider.go, website/docs/index.html.markdown
* use the Hashicorp retryable-http library by default
* add new configuration parameter `retry_max` to tune or disable the retries
* documentation updates
=> INBOX-2241/Add retries to Terraform provider

ns1/resource_record.go, ns1/resource_record_test.go
* CAA records with multiple parameters are now parsed correctly and can be written to the API.
=> INBOX-2221/fix CAA answer parsing

CHANGELOG.md, ns1/config.go
BUG FIXES
* Fixed CAA record answers to allow answers with spaces after a domain  ([issue 238](https://github.com/ns1-terraform/terraform-provider-ns1/issues/238))
* Upgrade to ns1-go v2.7.2 to get messages from HTTP 50x errors properly displayed.
* Upgraded to Terraform SDK 1.17.2
* Misc documentation fixes.
=> release 1.13.2-pre3

CHANGELOG.md, ns1/config.go
BUG FIXES
* Fixed CAA record answers to allow answers with spaces after a domain  ([issue 238](https://github.com/ns1-terraform/terraform-provider-ns1/issues/238))
* Upgrade to ns1-go v2.7.2 to get messages from HTTP 50x errors properly displayed.
* Upgraded to Terraform SDK 1.17.2
* Misc documentation fixes.
=> release 1.13.2-pre4

CHANGELOG.md, ns1/config.go
ENHANCEMENTS
* The [Hashicorp go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) package is now used by default to retry requests when encountering 502/503 errors or connection errors.
* Upgraded to Terraform SDK 1.17.2
* Upgraded to ns1-go 2.7.2
BUG FIXES
* Fix recognition of datafeed "not found" errors.
* Fixed CAA record answers to allow answers with spaces after a domain  ([issue 238](https://github.com/ns1-terraform/terraform-provider-ns1/issues/238))
* HTTP 50x and similar errors are now properly displayed.
* API keys can now be imported.
* Documentation corrections and updates.
* Fixed rate-limit divide-by-zero error.
=> release 1.13.2

CHANGELOG.md, ns1/config.go
ENHANCEMENTS
* The [Hashicorp go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) package is now used by default to retry requests when encountering 502/503 errors or connection errors.
* Upgraded to Terraform SDK 1.17.2
* Upgraded to ns1-go 2.7.2
BUG FIXES
* Fix recognition of datafeed "not found" errors.
* Fixed CAA record answers to allow answers with spaces after a domain  ([issue 238](https://github.com/ns1-terraform/terraform-provider-ns1/issues/238))
* HTTP 50x and similar errors are now properly displayed.
* API keys can now be imported.
* Documentation corrections and updates.
* Fixed rate-limit divide-by-zero error.
=> release 1.13.3

CHANGELOG.md, ns1/config.go
BUG FIXES
* fixed permissions problems with DNS record allow/deny lists (issues #196 and #197)
=> release 1.13.4-pre1

ns1/config.go, ns1/data_source_record.go, ns1/data_source_zone.go, ns1/resource_apikey.go, ns1/resource_apikey_test.go, ns1/resource_datafeed.go, ns1/resource_monitoringjob.go, ns1/resource_monitoringjob_test.go, ns1/resource_notifylist.go, ns1/resource_notifylist_test.go, ns1/resource_record_test.go, ns1/resource_team.go, ns1/resource_team_test.go, ns1/resource_user.go, ns1/resource_user_test.go
* add missing fields to datasource schemas
* use temporary variables for type conversion instead of trying to change the value in a schema
* fix tests that weren't testing the right record name
* fix HTTP debug mode to prevent panic when retry failure occurs
* detect missing resources by using 404 status instead of unreliable scraping of API text responses
=> INBOX-2198/fix issues discovered by sdk2 testing

.github/workflows/issue_notify.yml, .github/workflows/pr_notify.yml, .github/workflows/release.yml, .github/workflows/test-pr.yml
Node.js 12 actions are deprecated. Updated the following actions to use Node.js 16:
atlassian/gajira-login, atlassian/gajira-find-issue-key, atlassian/gajira-create, etc
=> RE-1556 : updated workflow issues

CHANGELOG.md, README.md, ns1/config.go, website/docs/index.html.markdown
ENHANCEMENTS
* User-agent string can now be customized in the resource file.
* Upgraded to ns1-go 2.7.3
BUG FIXES
* Fixed permissions problems with DNS record allow/deny lists (issues 196 and 197)
* Fixed a few cases where objects deleted from infrastructure but still in state were not being recognized correctly.
* Fixed error in HTTP response debug logging
* Datasource and datafeed schema fixes
=> release 1.13.4

CHANGELOG.md, ns1/config.go
ENHANCEMENTS
* Upgraded to Terraform SDK 2.24.1. Users of Pulsar will need to make minor changes in their resource files, see below.
INCOMPATIBILITIES WITH PREVIOUS VERSIONS
* The `ns1_application` resource attributes `config`, `default_config` and `blended_metric_weights` are now blocks, with only one item permitted. This is due to an SDK 2.x restriction on nested structures. Existing resource files will need to be edited to remove the equals sign in the declarations of the affected stanzas.
=> release 2.0.0-pre1

CHANGELOG.md, ns1/config.go
This Pr creates a release based on the current pre-release.
Notable changes:
- Upgraded to Terraform SDK 2.24.1
- Added `networks` resource 
There are some incompatibilities with previous versions, noted in the Changelog.
=> Release v2.0.0

CHANGELOG.md, go.mod, go.sum, ns1/config.go
BUG FIX
* `ns1-go` client version bump fixes `additional_metadata` not applying correctly
Note:
* To avoid whitespace issues in `additional_metadata` meta tag using `jsonencode` for example:
``` hcl
meta = {
"additional_metadata" : jsonencode(
[
{
a = "1"
b = "3"
}
])
}
=> Release v2.0.1

CHANGELOG.md, go.mod, go.sum, ns1/config.go
This PR bumps the NS1 Golang SDK client from v2.7.7 to v2.7.8 to correct monitor creation
=> release v2.0.5

CHANGELOG.md, go.mod, go.sum, ns1/config.go
`ns1-go` client version bump to fix omitting tags
=> Bump ns1-go to 2.9.1

ns1/resource_notifylist.go, ns1/resource_notifylist_test.go
We don't want Terraform updates that are just reordering the list; a bug upstream was partly fixed in November but null elements are still popping up when using TypeSet, so adding some safety check to exclude them.
=> Use TypeSet for notifications so that a change in order won't cause an update

ns1/resource_record.go
=> Regions to be an unordered TypeSet

CHANGELOG.md, ns1/config.go, ns1/resource_record.go, ns1/resource_record_test.go
DESCRIPTION: receiving 400 errors when trying to update or modify regions (answer groups) with the new version of the Terraform provider.  Adding answer groups to a record currently works
The main issue is that TF can add empty elements in sets, so fixing that by ignoring elements where the name is empty.
Also the need to update tags and blocked_tags at the same time has been overcome, so removing that check.
Right now TestAccRecord_meta and TestAccRecord_meta_with_json are failing for me (on a PUT /v1/monitoring/jobs), but I get the same result with the master branch so it seems unrelated.
=> Fix regions update

CHANGELOG.md, ns1/config.go, ns1/resource_redirect.go, ns1/resource_redirect_test.go
/fixes https://github.com/ns1-terraform/terraform-provider-ns1/issues/326
Updating regexes for the validation of redirect fields to reflect what is currently supported in NS1
=> #326: review redirect validation regexes

CHANGELOG.md, ns1/config.go, ns1/resource_redirect.go
The redirects APIs currently accept more characters in the target schema than Terraform does.
=> Expand allowed redirect targets character set

website/docs/r/redirect.html.markdown
Clarifying that if `certificate_id` is not specified the redirect is initially created HTTP, and recommending to set it explicitly if the certificate is managed by TF.
=> Redirect doc update

CHANGELOG.md, go.mod, go.sum, ns1/config.go, ns1/resource_record_test.go
Issue fixed in https://github.com/ns1/ns1-go/pull/236
We need to update to this version to fix it on our side; I also added a test for it.
=> Fix answer groups not wiped out

ns1/resource_record.go, ns1/resource_record_test.go
/fix #334
The root cause in the original ticket is probably null entries added by core TF in `each.value`, but we should avoid a crash regardless.
=> #334: protect against empty answers

CHANGELOG.md, examples/alert.tf, go.mod, go.sum, ns1/config.go, ns1/examples/alert.tf, ns1/provider.go, ns1/resource_alert.go, ns1/resource_alert_test.go, website/docs/r/alert.html.markdown, website/ns1.erb
This PR adds supports for the v1beta1 alerts api.
- Adds new resource types for alerts.
- Adds testcases.
- Adds examples.
~~This PR will need updating once https://github.com/ns1/ns1-go/pull/244 is merged there.~~
=> Add support for the v1beta1 alerts api.

CHANGELOG.md, ns1/config.go, ns1/resource_apikey.go, ns1/resource_apikey_test.go, website/docs/r/apikey.html.markdown
Issue: https://github.com/ns1-terraform/terraform-provider-ns1/issues/340
API Keys are only visible on create, which means they get removed from the state file if they get updated at all due to the empty response for `key` on update.
This fix keeps the api key in the state file.
=> Fix to prevent api key from being removed from the state file when the key is updated

ns1/resource_notifylist.go, ns1/resource_notifylist_test.go, website/docs/r/notifylist.html.markdown
The implementation of webhook headers is not ideal, because all members of `config` are currently defined as strings.
Trying to be backwards compatible the most I can do is document the poor encoding.
=> fix: headers cannot be added to notifiers
